### ISSUE TITLE
How to extend the model to UR robots?

### ISSUE THREAD

**Issue by laiyuzhi** [jingpeilu/CtRNet-robot-pose-estimation#7]
Hi! Fantastic work! 

I would really like to combine your approach with our latest project, but I don't have a panda robot, I only have multiple different models of UR robots at the moment. How do I create a dataset and train a model suitable for my camera and robot using an existing robot? Can you briefly describe what all I need to do?

**Comment by laiyuzhi** [comment]
In addition, how can I use my own data to pre-train the model?

**Comment by normajeane-m** [comment]
@laiyuzhi @jingpeilu 

Thank you for the excellent research and implementation. This is the same question as before, but since the previous thread was closed, I’m asking again. 
Is it possible to extend this to other robots such as Universal Robot?

**Comment by laiyuzhi** [comment]
Hi, to extend this approach to other robot, we need to generate new data and train a new model.
