### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by bschen22** [jingpeilu/CtRNet-robot-pose-estimation#8]
Hi! Fantastic work!
Can I ask how much time you spent using the Nvidia RTX 3090 when training 1000 epochs with all the Panda synthetic dataset?Can you share me the weight which is pretrained in the Panda synthetic data?
In the weight.zip, just found the weights after self-supervised.
My email, cbs001222@gmail.com,Thanks

**Comment by jingpeilu** [comment]
Thank you for liking our work! We trained the network on RTX A6000 GPU and the training time was around 1-2 weeks. Unfortunately, we don't have the weights before self-training.
